name: Pull Request Quality Gate

on:
  pull_request:
    branches:
      - master

jobs:
  quality_gate:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze code
        run: echo "Realizando análisis de SAST"
      
      - name: Check requirements
        id: check_requirements
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "Permitiendo Pull Request"
             echo "allow_pull=true" >> $GITHUB_ENV
          else
            echo "Impidiendo Pull Request"
            echo "allow_pull=false" >> $GITHUB_ENV
            exit 1
          fi
      
      - name: Allow build if pull is allowed
        if: env.ALLOW_PULL == 'true'
        run: echo "Permitiendo Pull Request"
      
      - name: Fail build if pull is not allowed
        if: env.ALLOW_PULL != 'true'
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1
      
      - name: Save allow_pull_request.txt as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allow_pull_request
          path: allow_pull_request.txt
