name: Pull Request Quality Gate

on:
  pull_request:

jobs:
  quality_gate:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze code
        run: echo "Realizando análisis de SAST"
      
      - name: Check requirements
        id: check_requirements
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "Permitiendo Pull Request"
            echo "::set-output name=allow_pull::true"
          else
            echo "Impidiendo Pull Request"
            echo "::set-output name=allow_pull::false"
            exit 1
          fi
      
      - name: Allow build if pull is allowed
        if: steps.check_requirements.outputs.allow_pull == 'true'
        run: echo "Permitiendo Pull Request"
      
      - name: Fail build if pull is not allowed
        if: steps.check_requirements.outputs.allow_pull != 'true'
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1
      
      - name: Save allow_pull_request.txt as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allow_pull_request
          path: allow_pull_request.txt
